package sc;

import java.applet.AudioClip;
import java.awt.event.ActionEvent;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;

/**
 * Esta clase observa los valores de la puntuación de la clase ControlCliente() la cual los
 * ha recibido del servidor. Muestra en el marcador el valor de la puntuación
 * @author: ROBERTO PÉREZ LLANOS
 * @version: 19/06/2016
 */

public class VentanaMarcador extends javax.swing.JFrame implements Observer{
    boolean stop=false;
    int n,pun=0,i=1,limite=1,limite2, pasoNivel=4;
    public VentanaMarcador() {
        initComponents();
        this.setTitle("Marcador");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puntos = new javax.swing.JLabel();
        TituloMarcador = new javax.swing.JLabel();
        stopBotton = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        nivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setLocation(new java.awt.Point(630, 100));

        puntos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        puntos.setText("0");

        TituloMarcador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TituloMarcador.setText("Puntuación");

        stopBotton.setBackground(new java.awt.Color(255, 0, 0));
        stopBotton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        stopBotton.setText("Parar Juego");
        stopBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBottonActionPerformed(evt);
            }
        });

        nivel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nivel.setText("Ronda 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TituloMarcador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(puntos)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(stopBotton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puntos)
                    .addComponent(TituloMarcador))
                .addGap(34, 34, 34)
                .addComponent(nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(stopBotton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBottonActionPerformed
        this.stop=true;
    }//GEN-LAST:event_stopBottonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloMarcador;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel nivel;
    private javax.swing.JLabel puntos;
    private javax.swing.JButton stopBotton;
    // End of variables declaration//GEN-END:variables

    /**
    * Este método se ejecuta cuando cambia algún parámetro del objeto cc2 de la clase ControlCliente()
    * Refleja en el marcador el valor de la puntuación.
    */
    public void actionPerformed(ActionEvent evt){
        n= jProgressBar1.getValue();
    }
    public void update(Observable o, Object arg) {
        ControlCliente cc2 = (ControlCliente) o;
        if(cc2.puntuacion==pun){
            jProgressBar1.setValue(n);
            n=n+25;
            pun++;
            if (cc2.puntuacion==pasoNivel){
                pasoNivel=pasoNivel+4;

                i++;
                nivel.setText("Ronda: "+i);
                AudioClip s1;
                s1= java.applet.Applet.newAudioClip(getClass().getResource("/sc/limites.wav"));
                s1.play();
                n=0;
                jProgressBar1.setValue(n);
                n=25;
            }
        }
        if (stop){
            cc2.parar();
            stop=false;
            stopBotton.setText("Juego Parado");
            JOptionPane.showMessageDialog(this,"Has finalizado la partida","Aviso",JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }else puntos.setText(String.valueOf(cc2.puntuacion));
    }
    
}